version: '3.8'
services:
  dwh:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dwh
    ports:
      - '5499:5432'
    volumes:
      - dwh:/var/lib/postgresql/data
volumes:
  dwh:
    driver: local